"""empty message

Revision ID: 13620aa99955
Revises: 329813138bf0
Create Date: 2023-04-20 12:22:47.048986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13620aa99955'
down_revision = '329813138bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
