"""empty message

Revision ID: 329813138bf0
Revises: 9a11cf0617e1
Create Date: 2023-04-18 18:02:12.850003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329813138bf0'
down_revision = '9a11cf0617e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork')
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.drop_column('image')

    op.create_table('artwork',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('artwork_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['art.art_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
