"""empty message

Revision ID: 3e55864c8520
Revises: 329813138bf0
Create Date: 2023-04-18 18:10:57.649206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e55864c8520'
down_revision = '329813138bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
