"""empty message

Revision ID: 9a11cf0617e1
Revises: fe54ef5c3461
Create Date: 2023-04-18 17:48:24.382423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a11cf0617e1'
down_revision = 'fe54ef5c3461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
