"""empty message

Revision ID: ab1b2f0cf4e7
Revises: 140f5abcd690
Create Date: 2023-04-21 02:43:11.947724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1b2f0cf4e7'
down_revision = '140f5abcd690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('artwork_id')

    # ### end Alembic commands ###
